version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
    ports:
      - "3000:3000"

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src
    expose:
      - "2048"
    volumes:
      - .:/go/src
    links:
      - redis

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src
    expose:
      - "2048"
    volumes:
      - .:/go/src
    links:
      - redis

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src
    expose:
      - "2048"
    volumes:
      - .:/go/src
    links:
      - redis

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src
    expose:
      - "2048"
    volumes:
      - .:/go/src
    links:
      - redis

  redis:
    image: redis:alpine
